language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
install: pip install pybuilder
script: pyb clean install_dependencies publish
after_success:
  - if [[ $ENV != python=3.1* ]]; then
      coveralls;
    fi